[package]
name = "basic-bms"
version = "0.1.0"
authors = ["Mason Boeman <masonboeman@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.11.0"
regex = "1"
lazy_static = "1.4.0"